// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Menu struct {
	ID          uuid.UUID   `json:"id"`
	Category    string      `json:"category"`
	MenuItemIds []uuid.UUID `json:"menu_item_ids"`
}

type Menuitem struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Price    int32     `json:"price"`
	ImageUrl string    `json:"image_url"`
	MenuID   uuid.UUID `json:"menu_id"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	PhoneNumber string    `json:"phone_number"`
	Password    string    `json:"password"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
